name: Resume CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image with run number
      run: docker build . -f Dockerfile -t my-image-name:${{ github.run_number }}

    - name: Build Docker image with latest tag
      run: docker build . -f Dockerfile -t my-image-name:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    - name: Tag images for Docker Hub
      run: |
        docker tag my-image-name:${{ github.run_number }} ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}
        docker tag my-image-name:latest ${{ secrets.REGISTRY_USERNAME }}/my-image-name:latest

    - name: Push images to Docker Hub
      run: |
        docker push ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}
        docker push ${{ secrets.REGISTRY_USERNAME }}/my-image-name:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 35.173.204.200
        username: ec2-user
        key: ${{secret.Key}}
        script: |
          docker stop resume || echo ""
          docker rm resume || echo ""
          docker run -d --name resume -p 8080:5001 ${{ secrets.REGISTRY_USERNAME }}/my-image-name:latest
